### PR TITLE
Adding more cost-related units and cleaning up

### PR DESCRIPTION
**Pull request by mschmitz2**
#39

### CODE REVIEW

**Comment by mschmitz2** [comment]
@MadsKirkFoged I only meant to add the first 4 commits to this pull request. Didn't think the others would show up in here after I created the pull request. I guess next time I'll create a specific branch for each pull request... In any case, the last 3 commits are just cleaning up some of the namespaces with no other changes, so feel free to add these changes as well or ignore them

**Comment by MadsKirkFoged** [comment]
Good job Max! And nice with the cleanup

**Comment by mschmitz2** [comment]
Yeah no worries.. could eventually do the same kind of cleanup for all combined units, but I restrained myself.. for now. 
In any case, I'll be happy to contribute more to this is the future

**Comment by MadsKirkFoged** [comment]
Feel free to do as much cleanup as you want!
Also if you find other places in the code you think needs a refactoring.

I would one day love to get a better structure in the Unittest project. 
Right now they are all just shoveled in.

**Pull request merged**
